networks:
    laravel:
        driver: bridge

services:
    php:
        build:
            context: .
            dockerfile: .docker/php-fpm/Dockerfile
        container_name: ${COMPOSE_PROJECT_NAME}_php
        restart: unless-stopped
        volumes:
            - .:/var/www
            - ./.docker/php-fpm/php-dev.ini:/usr/local/etc/php/conf.d/php.ini
        depends_on:
            - mysql
            - redis
        ports:
            - "9000:9000"
            - "5173:5173"
        environment:
            - APP_ENV=local
        networks:
            - laravel

    nginx:
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        restart: unless-stopped
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 3
        networks:
            - laravel

    redis:
        image: redis:alpine
        container_name: ${COMPOSE_PROJECT_NAME}_redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel

#    mailcatcher:
#        image: schickling/mailcatcher
#        ports:
#            - "1025:1025"
#            - "1080:1080"
#        networks:
#            - laravel

volumes:
    mysql_data:
